### ISSUE TITLE
Server.js

### ISSUE THREAD

**Issue by Axkaban** [chethanshettar/ca-project-3-the-scoop#1]
49 passing tests! Well done.

Routes look immaculate! As you start working with Express, you will see that routes are one of the easiest(yet tricky) parts of back-end development, Express handles them as methods, for example, you have .get() that will take two arguments, the first one is a string of the route: `'/articles'` and the second is the function, like your getArticles() function.

Also, if you notice, the structure of the createComment function [https://github.com/chethanshettar/ca-project-3-the-scoop/blob/master/server.js#L49-L76](https://github.com/chethanshettar/ca-project-3-the-scoop/blob/master/server.js#L49-L76)
is almost identical to createArticle [https://github.com/chethanshettar/ca-project-3-the-scoop/blob/master/server.js#L255-L281](https://github.com/chethanshettar/ca-project-3-the-scoop/blob/master/server.js#L255-L281)
That is also common in server side programming, but as you go along, you provide a file for each task, in that case comments will have their file, articles they own, and users will have a file as well, if you were to have actions that repeat identically, you can create an extra file with those actions turned into functions and call them when needed. That is middleware.

A suggestion that I can make is when you are building an object that has the key being the same as the value like here: 
[https://github.com/chethanshettar/ca-project-3-the-scoop/blob/master/server.js#L274](https://github.com/chethanshettar/ca-project-3-the-scoop/blob/master/server.js#L274)
this: `response.body = {article: article};`
can be re-written: `response.body = {article};` because javascript already has the capacity to say "since there is one value passing I will use it for both positions". It saves you personal time, and it looks cleaner.

**Comment by chethanshettar** [comment]
Thanks for the review!
