### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [chethanshettar/ca-project-3-the-scoop#2]
Grade: **Meets Expectations and requirements**

Awesome job! as you keep on working on future projects, have in mind, what can you make into middleware? Even if they are functions in the same file but that you can reuse in many parts of your code.

Here's a little intro to routing from the Express docs: [https://expressjs.com/en/guide/routing.html](https://expressjs.com/en/guide/routing.html)

Best of luck!

**Comment by chethanshettar** [comment]
I will take a look. Thanks for the review!
